spring.application.name=pertemuan11

# 1. Konfigurasi Koneksi Database PostgreSQL (Docker)
# Menggunakan port 5434, nama database praktikum_db, user praktikum_user, dan password 12345 sesuai isi docker-compose
spring.datasource.url=jdbc:postgresql://localhost:5434/praktikum_db
spring.datasource.username=praktikum_user
spring.datasource.password=12345

# 2. Driver PostgreSQL yang digunakan
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Dialek Database untuk Hibernate (PostgreSQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 4. Fitur Auto-Update Struktur Tabel
# Hibernate akan otomatis membuat tabel 'users' dan 'profile' di PostgreSQL saat aplikasi dijalankan
spring.jpa.hibernate.ddl-auto=update

# 5. Log Query SQL ke Console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true